services:
  - type: web
    name: y2k-portfolio-app
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh

  - type: static
    name: y2k-portfolio-static
    publishDir: dist
    buildCommand: npm install && npm run build
